CREATE TABLE IF NOT EXISTS msgs (
	id          SERIAL PRIMARY KEY,
	name        VARCHAR(100) NOT NULL,
	email       CITEXT NOT NULL,
	body        TEXT NOT NULL,
	created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
